package com.miu.onlinemarketplace.common.enums;

public enum MailType {
    SIGNUP_VERIFICATION_CODE,
    FORGOT_PASSWORD_REQUEST_CODE,
    PASSWORD_CHANGE_NOTIFICATION,
    ACCOUNT_APPROVE,
    ACCOUNT_SUSPEND,
    ORDER_CONFIRMED,
    ORDER_CANCELED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    PAYMENT_FAIL
}
