spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pmdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Root@1234}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      fail-on-empty-beans: false

app:
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:8080
  jwt:
    secret-key: ${JWT_SECRET_KEY:pm490-proj-secret}
    expire-seconds: 86400
  mail:
    host: ff.ff
    port: 1
    username: dd
    password: dsd

minio:
  bucket:
    name: pmstorage
  access:
    key: gQUrVcSt8Y5d3060
    secret: h5ZUzOckMPBBC1Adx46tdyeaor1g2xfQ
  url: http://127.0.0.1:9000

